container_name: mastodon-harvestor
image_name: djang9303/mastodon-harvestor
image_tag: 1.4

token_social: Hjv8XHIQMo042o7nTXbWC15WkUtWUd9bekh6s5lz-L0
token_au: pwvGgbL4Kapd2kYQGTWd20ZqcHP0lTqR9ioyDNlihPo
token_cloud: B0T98uen8Mt4I-xygsG_CVX3e54m1DFGJMUdpjRXZq4
token_world: bGflW2L837cKzBEb36_8Hl6SuGQ0d6AaWgrsrx7ij3I
token_uk: Ep6V4XkMGxFtokagetZAffCotR9ZVk-7Nffto-Oio3k

swarm_manager_ip: 172.26.136.158
remote_addr: "172.26.136.158:2377"