#
# Part of Assignment 2 - COMP90024 course at The University of Melbourne 
#
# Cluster and Cloud Computing - Team 43 
# 

- hosts: localhost
  vars_files:
    - host_vars/mrc_instances.yaml
  gather_facts: true

  roles:
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

