# Install Docker and CouchDB
- hosts: DataNodes
  vars_files:
    - host_vars/couchdb_settings.yaml
  gather_facts: true

  roles:
    - role: nodes-common
    - role: nodes-docker-install
    - role: nodes-volume-mount
    - role: git-clone
    - role: couchdb-setup

 # Perform CouchDB configuration on all hosts except Masternode
- hosts: DataNodes:!Masternode
  vars_files:
    - host_vars/couchdb_settings.yaml
  gather_facts: true

  tasks:
    - name: Change file permissions
      file:
        path: ~/code/CCC2/Deployment/Couch_Setup/worker_script.sh
        mode: '+x'

    - name: Run script
      script: ~/code/CCC2/Deployment/Couch_Setup/worker_script.sh
    
