#
# Part of Assignment 2 - COMP90024 course at The University of Melbourne
#
# Cluster and Cloud Computing - Team 43
#

# Common vars
availability_zone: melbourne-qh2-uom
instance_image: bbaf16f8-2484-48d7-b455-42209cc4b8d2
instance_key_name: Svar
instance_flavor: uom.mse.1c4g

# Volume
volumes:
  - vol_name: volume-1
    vol_size: 20
  - vol_name: volume-2
    vol_size: 20
  - vol_name: volume-3
    vol_size: 20

# Security group
security_groups:
  - name: administration
    description: "Security group for remote access via SSH or HTTP "
  - name: couch_cluster
    description: "Security group for communication between CouchDB nodes in cluster"
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

security_group_rules_public:
  - name: administration
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: administration
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: administration
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: administration
    protocol: tcp
    port_range_min: 8000
    port_range_max: 8000
    remote_ip_prefix: 0.0.0.0/0

security_group_rules_private:
  - name: couch_cluster
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_group: couch_cluster
  - name: couch_cluster
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_group: couch_cluster
  - name: couch_cluster
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_group: couch_cluster

# Instance
instances:
  - name: couch-master-0
    volumes: ['volume-1']
  - name: couch-worker-1
    volumes: ['volume-2']
  - name: couch-worker-2
    volumes: ['volume-3']
  - name: python-1
    volumes: []
  - name: python-2
    volumes: []
  - name: harvester-master
    volumes: []
  - name: harvester-worker
    volumes: []
